# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bed4ec7b93f951bf5630ddef5091ec5906bd1342ba9a51a6db1eb0266cc5a7b3120b623c42d8b848764b956fd4bb1cba4f344491f775c490eb8097446a3521b2

test:
  secret_key_base: 7ba45c2e733643b54d4a7a1a49cde204768d13ed5b6e57f3b034eca6c4a69e1a8251cdf86114e4397a834abf322b0fb6488bbd12cc899af25d1654c22c2cfc86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
